### PR TITLE
Add differences section to readme

### PR DESCRIPTION
**Pull request by Miosame**
Went through multiple iterations of this, trying to avoid to duplicate what's said in the introduction already, yet making clear what this provides to users out of the box. Maintainer edits are checked.

### CODE REVIEW

**Comment by zacksmash** [comment]
So, I added in a section for this, which I think aligns better with the purpose of this package. I don't know that it's a successor to Laravel UI, since Taylor mentioned today that it will continue to work with future versions of Laravel. I hope it helps give clarity as to what I'm trying to do here. 🤪

Thanks for the PR, though!

**Comment by Miosame** [comment]
@zacksmash (just saw the taylor video published, wasn't aware prior to this)
Even if laravel/ui is supposed to be maintained "indefinitely" (though that can easily change in the future) - fortify is the way to go now, so imho it's still a successor building on top of what was laravel/ui and now on the modern fortify approach. (hopefully that makes sense) :wink: 

On the note of the readme change: now it still misses that FortifyUI adds all the things that fortify misses and notes down as "implement it yourself", e.g. 2FA/password-change and alikes - which was the "breaking point" of why this makes more sense to use over "just" following the fortify readme (avoiding the usual "why do I need another package for this?" and "does this just automate the basics and I still anyway need to implement X?") :sweat_smile:

**Comment by zacksmash** [comment]
Both very good points. Dang... Let's see if we can add to what's there. I'd rather not mention Laravel UI, though. I'll let the Laravel team figure out the future of that, but you're right: Fortify is the future.

**Comment by Miosame** [comment]
@zacksmash sure that's fine, I wasn't trying to take a stab at those projects, it's just common speech to say something along those lines and also I guess has the side-effect of people finding this project if they search for alternatives.

**Comment by Miosame** [comment]
@zacksmash looking at the current state of the readme (not sure if you're still editing)
- "scaffoling" => "scaffolding"

otherwise great stuff! now I can just straight link people to that subheader :partying_face:
thanks for the so quick responses and this project! :tada:

**Pull request closed without merging**
